#!/bin/bash

#NODE_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f2)
QEMUVER=$(echo $DOCKER_TAG)

if [ $DOCKER_TAG == "latest" ]
then
  docker build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
else
  #docker build . --build-arg NODE_VERSION=${NODE_VERSION} -t ${IMAGE_NAME}
  docker build . --build-arg QEMUVER=${DOCKER_TAG} -t ${IMAGE_NAME}
fi
